# Generated by Django 3.1.7 on 2021-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='person',
            name='fio',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='person',
            name='service',
            field=models.CharField(blank=True, choices=[('Онлайн консультация юриста', 'Онлайн консультация юриста'), ('Онлайн консультация бухгалтера', 'Онлайн консультация бухгалтера')], max_length=255, null=True, verbose_name='Услуга'),
        ),
    ]
